# Generated by Django 6.0.3 on 2026-03-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_line', models.CharField(max_length=50)),
                ('origin_port_name', models.CharField(max_length=100)),
                ('destination_port_name', models.CharField(max_length=100)),
                ('container_size', models.CharField(max_length=50)),
                ('kgs', models.IntegerField()),
                ('valid_from_etd', models.DateField(blank=True, null=True)),
                ('valid_to_eta', models.DateField(blank=True, null=True)),
                ('total_cost_usd', models.FloatField()),
            ],
        ),
    ]
