# Generated by Django 6.0.3 on 2026-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
