# Generated by Django 6.0.3 on 2026-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_shippingrate_date_shippingrate_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='kgs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='total_cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
