# Generated by Django 6.0.3 on 2026-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_alter_shippingrate_kgs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='valid_from_etd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='valid_to_eta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
