# Generated by Django 6.0.3 on 2026-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_alter_shippingrate_valid_from_etd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='export_surcharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='freight_surcharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='import_surcharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='ocean_freight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='container_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='destination_port_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='origin_port_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='shipping_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='valid_from_etd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='valid_to_eta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
